//! `localmem init` handler.
//!
//! Scaffolds a fresh localmem home directory. See SPEC.md "localmem init"
//! for the contract: idempotent, refuses to clobber a non-empty
//! `events.jsonl`, creates the derived/policies/keys/cache tree, writes
//! a default config.toml and a copy of the bundled default policy.

use crate::event_log::EVENTS_FILE;
use crate::policy::{DEFAULT_POLICY_FILE, DEFAULT_POLICY_YAML, POLICIES_DIR};
use anyhow::{Context, Result};
use serde::Serialize;
use std::path::{Path, PathBuf};
use tracing::info;

/// Default embedder model slug. Mirrors `fetch_model::DEFAULT_MODEL_SLUG`
/// so a fresh `init` knows which subdirectory to look for under the
/// global home. Kept private here; the embedder code paths still
/// resolve the slug via `resolve_model_dir` per-handler.
const DEFAULT_EMBEDDER_SLUG: &str = "bge-small-en-v1.5";
const DEFAULT_EMBEDDER_FILE: &str = "model.onnx";

/// Filename of the user-facing config file at the home root.
pub const CONFIG_FILE: &str = "config.toml";

/// v0.1 config.toml template. Mirrors SPEC.md "Configuration" section.
/// Embedded so `localmem init` can run before the user has any local files.
const CONFIG_TOML_TEMPLATE: &str = "# localmem config.toml (v0.1)
#
# Generated by `localmem init`. Edit freely. Every setting maps to an env
# var of the form LOCALMEM_<SECTION>_<KEY>. Example: setting
# `LOCALMEM_SERVER_ADDR=127.0.0.1:9999` overrides `[server].addr`.

[home]
version = 1

[embedder]
model = \"bge-small-en-v1.5\"
backend = \"onnx\"                  # onnx | ollama | none

[policy]
default = \"policies/default.yaml\"
user    = \"policies/user.yaml\"
llm_assist = false                # true enables local Ollama for ambiguous cases

[server]
addr = \"127.0.0.1:7788\"
unix_socket = \"\"                  # optional, takes precedence if set

[sync]
enabled = false                   # opt-in, never default true
endpoint = \"\"
key_file = \"keys/master.key\"

[telemetry]
enabled = false                   # opt-in always
";

/// Outcome reported by [`init_home`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum InitResult {
    /// New home scaffolded.
    Created,
    /// `events.jsonl` was already present and non-empty; nothing was changed.
    AlreadyInitialized,
}

/// Entry point for the `init` subcommand.
pub fn run(home: Option<&str>, as_json: bool) -> Result<()> {
    let home = resolve_home(home)?;
    let result = init_home(&home)?;
    emit(&home, result, as_json)?;
    // Capability #5: surface any detected memory exports on a fresh
    // init so the user knows they can run `localmem import-wizard
    // --apply` straight away. Quiet on AlreadyInitialized (the user
    // is past the onboarding moment) and on detection failure
    // (init must succeed even if the wizard hits an I/O error).
    if result == InitResult::Created && !as_json {
        if let Ok(detections) = crate::cli::import_wizard::scan_default_locations() {
            if !detections.is_empty() {
                println!();
                println!(
                    "Found {} potential memory source(s) to import:",
                    detections.len(),
                );
                for d in &detections {
                    let conf = match d.confidence {
                        crate::cli::import_wizard::Confidence::High => "HIGH",
                        crate::cli::import_wizard::Confidence::Low => "low",
                    };
                    println!("  [{conf}] {} :: {}", d.format, d.path.display());
                }
                println!();
                println!("Run `localmem import-wizard` to review, or `localmem import-wizard --apply` to ingest them.");
            }
        }
    }
    Ok(())
}

/// Idempotent scaffold of a localmem home directory.
///
/// Refuses to clobber an existing non-empty `events.jsonl`: that file is
/// the source of truth and would only be overwritten by user error. The
/// directory tree, policy file, and config file are written defensively
/// (created only if missing) so re-running on an empty home is safe.
pub fn init_home(home: &Path) -> Result<InitResult> {
    let events = home.join(EVENTS_FILE);
    let already = events.metadata().map(|m| m.len() > 0).unwrap_or(false);
    if already {
        return Ok(InitResult::AlreadyInitialized);
    }

    std::fs::create_dir_all(home)
        .with_context(|| format!("create home dir at {}", home.display()))?;
    for sub in ["derived", POLICIES_DIR, "keys", "cache", "models"] {
        std::fs::create_dir_all(home.join(sub))
            .with_context(|| format!("create {sub}/ under {}", home.display()))?;
    }

    // Touch events.jsonl so EventLog::open finds it. Append-mode open
    // matches the on-disk semantics used by the rest of the system.
    std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&events)
        .with_context(|| format!("create events.jsonl at {}", events.display()))?;

    // Default policy: write the bundled YAML. The user policy is left
    // absent so its non-existence is informative ("no overrides applied").
    let policy_path = home.join(POLICIES_DIR).join(DEFAULT_POLICY_FILE);
    if !policy_path.exists() {
        std::fs::write(&policy_path, DEFAULT_POLICY_YAML)
            .with_context(|| format!("write default policy at {}", policy_path.display()))?;
    }

    let config_path = home.join(CONFIG_FILE);
    if !config_path.exists() {
        std::fs::write(&config_path, CONFIG_TOML_TEMPLATE)
            .with_context(|| format!("write config.toml at {}", config_path.display()))?;
    }

    // Field-feedback fix (P2, 2026-06-04): share the embedder model
    // from the user's global home (`~/.localmem`) into the new home
    // so per-project stores ship with vector-backed hybrid search out
    // of the box. Without this, a fresh `localmem init --home
    // <project>/.localmem` warns "embedder unavailable" on every
    // write and `localmem search` silently degraded to lex; the
    // workaround in the field report was a manual symlink + replay.
    //
    // Best-effort: any error linking is logged at INFO and init still
    // succeeds. The new home remains usable lex+facts-only and can
    // gain vectors later via `localmem fetch-model` + `localmem
    // replay`.
    let global_home = resolve_global_home();
    if let Err(e) = link_embedder_from(global_home.as_deref(), home) {
        info!(
            error = %e,
            "could not share global embedder model; new home will be lex+facts only until \
             `localmem fetch-model` is run"
        );
    }

    Ok(InitResult::Created)
}

/// Resolve `~/.localmem` from `$HOME`. Returns `None` when `$HOME` is
/// unset (the test harness sometimes unsets it; the production CLI
/// gates on it elsewhere).
fn resolve_global_home() -> Option<PathBuf> {
    std::env::var("HOME")
        .ok()
        .filter(|s| !s.is_empty())
        .map(|h| PathBuf::from(h).join(".localmem"))
}

/// Share the embedder model from `global_home/models/<slug>/` into
/// `home/models/<slug>/` when both:
/// 1. `global_home` is set and its model file exists, AND
/// 2. `home` is not the same path as `global_home` (don't link to
///    ourselves), AND
/// 3. `home/models/<slug>/<file>` is not already present.
///
/// Pulled out of `init_home` with `global_home` as an explicit
/// parameter so tests can drive both branches without touching the
/// real `$HOME/.localmem`.
fn link_embedder_from(global_home: Option<&Path>, home: &Path) -> Result<()> {
    let Some(global_home) = global_home else {
        return Ok(());
    };
    let global_model_dir = global_home.join("models").join(DEFAULT_EMBEDDER_SLUG);
    let global_model_file = global_model_dir.join(DEFAULT_EMBEDDER_FILE);
    if !global_model_file.exists() {
        // No global model to share. Caller logs the next-step hint.
        return Ok(());
    }

    let new_home_canon = home.canonicalize().unwrap_or_else(|_| home.to_path_buf());
    let global_home_canon = global_home.canonicalize().unwrap_or_else(|_| global_home.to_path_buf());
    if new_home_canon == global_home_canon {
        // We ARE the global home; nothing to symlink to ourselves.
        return Ok(());
    }

    let local_model_dir = home.join("models").join(DEFAULT_EMBEDDER_SLUG);
    if local_model_dir.join(DEFAULT_EMBEDDER_FILE).exists() {
        // Already populated (e.g. previous init or manual install).
        return Ok(());
    }

    // The symlink target must point at a model directory that exists
    // on disk. If `local_model_dir` is a real (empty) directory left
    // by `init_home` above, remove it so `symlink` can lay down a
    // link in its place. `remove_dir` refuses non-empty dirs so we
    // never accidentally clobber a user-placed model.
    if local_model_dir.exists() {
        std::fs::remove_dir(&local_model_dir).with_context(|| {
            format!(
                "remove empty model dir {} before linking to global",
                local_model_dir.display()
            )
        })?;
    }

    #[cfg(unix)]
    {
        std::os::unix::fs::symlink(&global_model_dir, &local_model_dir).with_context(|| {
            format!(
                "symlink {} -> {}",
                local_model_dir.display(),
                global_model_dir.display()
            )
        })?;
    }
    #[cfg(not(unix))]
    {
        // Windows: copy is the safe portable choice; symlinks need
        // either admin or developer mode. v0.2 ships on macOS + Linux
        // first, so this branch is a placeholder for parity later.
        std::fs::create_dir_all(&local_model_dir)?;
        for entry in std::fs::read_dir(&global_model_dir)? {
            let entry = entry?;
            let dst = local_model_dir.join(entry.file_name());
            std::fs::copy(entry.path(), &dst)?;
        }
    }
    info!(
        from = %global_model_dir.display(),
        to = %local_model_dir.display(),
        "shared global embedder model into new home"
    );
    Ok(())
}

fn emit(home: &Path, result: InitResult, as_json: bool) -> Result<()> {
    if as_json {
        let json = serde_json::json!({
            "ok": true,
            "home": home.display().to_string(),
            "result": result,
        });
        println!("{json}");
    } else {
        match result {
            InitResult::Created => {
                println!("initialized localmem home at {}", home.display());
            }
            InitResult::AlreadyInitialized => {
                eprintln!(
                    "warning: {} already initialized (non-empty events.jsonl); leaving untouched",
                    home.display()
                );
            }
        }
    }
    Ok(())
}

fn resolve_home(override_: Option<&str>) -> Result<PathBuf> {
    if let Some(h) = override_.filter(|s| !s.is_empty()) {
        return Ok(PathBuf::from(h));
    }
    let home = std::env::var("HOME")
        .context("HOME environment variable is not set; pass --home explicitly")?;
    Ok(PathBuf::from(home).join(".localmem"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn init_fresh_home_creates_expected_tree() {
        let tmp = tempdir().unwrap();
        let result = init_home(tmp.path()).unwrap();
        assert_eq!(result, InitResult::Created);

        for sub in ["derived", "policies", "keys", "cache", "models"] {
            assert!(tmp.path().join(sub).is_dir(), "{sub}/ should exist");
        }
        assert!(
            tmp.path().join(EVENTS_FILE).exists(),
            "events.jsonl missing"
        );
        assert!(
            tmp.path()
                .join(POLICIES_DIR)
                .join(DEFAULT_POLICY_FILE)
                .exists(),
            "default.yaml missing"
        );
        assert!(tmp.path().join(CONFIG_FILE).exists(), "config.toml missing");
    }

    #[test]
    fn init_refuses_to_clobber_existing_log() {
        let tmp = tempdir().unwrap();
        // Plant a non-empty events.jsonl simulating a real localmem home.
        std::fs::write(tmp.path().join(EVENTS_FILE), b"{\"id\":\"01HX\"}\n").unwrap();
        let result = init_home(tmp.path()).unwrap();
        assert_eq!(result, InitResult::AlreadyInitialized);
    }

    #[test]
    fn init_on_empty_log_proceeds() {
        let tmp = tempdir().unwrap();
        // Zero-byte events.jsonl (e.g. from a prior init that wrote nothing
        // yet) should be treated as fresh; init proceeds.
        std::fs::write(tmp.path().join(EVENTS_FILE), b"").unwrap();
        let result = init_home(tmp.path()).unwrap();
        assert_eq!(result, InitResult::Created);
    }

    #[test]
    fn init_is_idempotent_on_empty_tree() {
        // Two inits in a row on an empty home: both should report Created
        // and neither should overwrite existing files.
        let tmp = tempdir().unwrap();
        assert_eq!(init_home(tmp.path()).unwrap(), InitResult::Created);
        // Mutate config.toml so we can prove init does not overwrite.
        let cfg = tmp.path().join(CONFIG_FILE);
        std::fs::write(&cfg, b"# user-edited\n").unwrap();
        assert_eq!(init_home(tmp.path()).unwrap(), InitResult::Created);
        let after = std::fs::read_to_string(&cfg).unwrap();
        assert_eq!(
            after, "# user-edited\n",
            "config.toml must not be clobbered"
        );
    }

    #[test]
    fn default_policy_yaml_round_trips_through_policy_loader() {
        // The bundled policy we write to disk must be parseable by the
        // same loader the engine uses. Catches a future drift between
        // policy.rs and the YAML.
        use crate::policy::Policy;
        let tmp = tempdir().unwrap();
        init_home(tmp.path()).unwrap();
        let policy = Policy::load(tmp.path()).unwrap();
        assert!(
            !policy.rules.is_empty(),
            "loaded policy should contain the bundled rules"
        );
    }

    // ---- global-model symlink (field-feedback P2, 2026-06-04) ---------

    /// Seed a fake global home with a model file at the canonical
    /// slug path. Returns the path of the model file written.
    fn seed_global_model(global: &Path) -> PathBuf {
        let model_dir = global.join("models").join(DEFAULT_EMBEDDER_SLUG);
        std::fs::create_dir_all(&model_dir).unwrap();
        let file = model_dir.join(DEFAULT_EMBEDDER_FILE);
        std::fs::write(&file, b"stub-onnx-bytes").unwrap();
        file
    }

    #[test]
    fn link_embedder_from_noop_when_global_home_none() {
        let tmp = tempdir().unwrap();
        let home = tmp.path();
        std::fs::create_dir_all(home.join("models").join(DEFAULT_EMBEDDER_SLUG)).unwrap();
        // No-op: returns Ok and leaves the local dir untouched.
        link_embedder_from(None, home).unwrap();
        assert!(home.join("models").join(DEFAULT_EMBEDDER_SLUG).is_dir());
        assert!(!home
            .join("models")
            .join(DEFAULT_EMBEDDER_SLUG)
            .join(DEFAULT_EMBEDDER_FILE)
            .exists());
    }

    #[test]
    fn link_embedder_from_noop_when_global_model_missing() {
        let tmp_global = tempdir().unwrap();
        let tmp_local = tempdir().unwrap();
        // Global home exists but has no model file.
        std::fs::create_dir_all(tmp_global.path().join("models")).unwrap();
        std::fs::create_dir_all(tmp_local.path().join("models").join(DEFAULT_EMBEDDER_SLUG))
            .unwrap();
        link_embedder_from(Some(tmp_global.path()), tmp_local.path()).unwrap();
        // Local model file remains absent; we did not invent one.
        assert!(!tmp_local
            .path()
            .join("models")
            .join(DEFAULT_EMBEDDER_SLUG)
            .join(DEFAULT_EMBEDDER_FILE)
            .exists());
    }

    #[test]
    fn link_embedder_from_symlinks_when_global_present() {
        let tmp_global = tempdir().unwrap();
        let tmp_local = tempdir().unwrap();
        let seeded = seed_global_model(tmp_global.path());
        std::fs::create_dir_all(tmp_local.path().join("models").join(DEFAULT_EMBEDDER_SLUG))
            .unwrap();
        link_embedder_from(Some(tmp_global.path()), tmp_local.path()).unwrap();

        // After link, the local model file resolves through the link
        // to the same byte content as the global one.
        let local_file = tmp_local
            .path()
            .join("models")
            .join(DEFAULT_EMBEDDER_SLUG)
            .join(DEFAULT_EMBEDDER_FILE);
        assert!(local_file.exists(), "local model file must resolve");
        let body = std::fs::read(&local_file).unwrap();
        let expected = std::fs::read(&seeded).unwrap();
        assert_eq!(body, expected);
    }

    #[test]
    fn link_embedder_from_skips_when_local_already_populated() {
        let tmp_global = tempdir().unwrap();
        let tmp_local = tempdir().unwrap();
        seed_global_model(tmp_global.path());
        // Pre-populate the local home with a DIFFERENT model file. We
        // must NOT clobber it with a symlink to the global one.
        let local_model_dir = tmp_local.path().join("models").join(DEFAULT_EMBEDDER_SLUG);
        std::fs::create_dir_all(&local_model_dir).unwrap();
        let local_file = local_model_dir.join(DEFAULT_EMBEDDER_FILE);
        std::fs::write(&local_file, b"USER-OWNED-bytes").unwrap();

        link_embedder_from(Some(tmp_global.path()), tmp_local.path()).unwrap();

        let body = std::fs::read(&local_file).unwrap();
        assert_eq!(
            body, b"USER-OWNED-bytes",
            "must not overwrite a user-placed model"
        );
    }

    #[test]
    fn link_embedder_from_skips_when_home_equals_global_home() {
        // Calling with home == global_home must be a no-op (don't
        // symlink the directory into itself).
        let tmp = tempdir().unwrap();
        let global_and_local = tmp.path();
        let seeded = seed_global_model(global_and_local);
        link_embedder_from(Some(global_and_local), global_and_local).unwrap();
        // The seeded file is still the seeded file; the dir was never
        // turned into a self-pointing symlink.
        assert!(seeded.exists());
        let meta = std::fs::symlink_metadata(global_and_local.join("models").join(DEFAULT_EMBEDDER_SLUG))
            .unwrap();
        assert!(
            !meta.file_type().is_symlink(),
            "must not symlink the global model dir to itself"
        );
    }
}
