//! `localmem service` — register the core as an OS-native auto-launch service so
//! the memory daemon is always running at login (Pillar 1 of the unified-memory
//! spec). launchd user agent on macOS, systemd `--user` unit on Linux.
//!
//! The service runs `localmem serve --dashboard` (the MCP API + the viewer). The
//! unit/plist CONTENT is generated by pure, testable functions; install/uninstall
//! shell out to the platform loader (`launchctl` / `systemctl --user`).

use anyhow::{bail, Context, Result};
use std::path::PathBuf;

/// launchd label / systemd unit stem. Reverse-DNS so it never collides.
const LABEL: &str = "dev.localmem.core";

pub fn run(action: &str, home: Option<&str>) -> Result<()> {
    match action {
        "install" => install(home),
        "uninstall" => uninstall(),
        "status" => status(),
        other => bail!("unknown service action {other:?}; use: install | uninstall | status"),
    }
}

/// The localmem binary the service should launch. `current_exe` resolves the
/// real target (following a dev symlink), which is what we want in the unit.
fn exe_path() -> Result<String> {
    Ok(std::env::current_exe()
        .context("resolve current executable")?
        .to_string_lossy()
        .into_owned())
}

fn resolve_home(override_: Option<&str>) -> PathBuf {
    if let Some(h) = override_.filter(|s| !s.is_empty()) {
        return PathBuf::from(h);
    }
    std::env::var("HOME")
        .map(|h| PathBuf::from(h).join(".localmem"))
        .unwrap_or_else(|_| PathBuf::from(".localmem"))
}

// ---------------------------------------------------------------------------
// Pure generators (testable without touching the OS)
// ---------------------------------------------------------------------------

/// launchd property list that runs the core at login and keeps it alive.
pub fn launchd_plist(exe: &str, log_path: &str) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>{exe}</string>
        <string>serve</string>
        <string>--dashboard</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>{log_path}</string>
    <key>StandardErrorPath</key>
    <string>{log_path}</string>
</dict>
</plist>
"#
    )
}

/// systemd `--user` unit that runs the core and restarts it on failure.
pub fn systemd_unit(exe: &str) -> String {
    format!(
        "[Unit]\n\
         Description=localmem core (local-first memory daemon)\n\
         After=network.target\n\n\
         [Service]\n\
         ExecStart={exe} serve --dashboard\n\
         Restart=always\n\
         RestartSec=2\n\n\
         [Install]\n\
         WantedBy=default.target\n"
    )
}

// ---------------------------------------------------------------------------
// macOS (launchd)
// ---------------------------------------------------------------------------

#[cfg(target_os = "macos")]
fn plist_path() -> Result<PathBuf> {
    let home = std::env::var("HOME").context("HOME not set")?;
    Ok(PathBuf::from(home)
        .join("Library/LaunchAgents")
        .join(format!("{LABEL}.plist")))
}

#[cfg(target_os = "macos")]
fn install(home: Option<&str>) -> Result<()> {
    let exe = exe_path()?;
    let log = resolve_home(home).join("serve.log");
    let path = plist_path()?;
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).context("create LaunchAgents dir")?;
    }
    std::fs::write(&path, launchd_plist(&exe, &log.to_string_lossy()))
        .with_context(|| format!("write {}", path.display()))?;
    let p = path.to_string_lossy().into_owned();
    // Reload idempotently: unload an existing one (ignore errors), then load.
    let _ = std::process::Command::new("launchctl")
        .args(["unload", &p])
        .output();
    let out = std::process::Command::new("launchctl")
        .args(["load", "-w", &p])
        .output()
        .context("run launchctl load")?;
    if !out.status.success() {
        bail!(
            "launchctl load failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    println!("✓ localmem service installed (launchd: {LABEL}).");
    println!("  It now starts at login and stays running.");
    println!("  plist: {p}");
    println!("  logs:  {}", log.display());
    Ok(())
}

#[cfg(target_os = "macos")]
fn uninstall() -> Result<()> {
    let path = plist_path()?;
    let p = path.to_string_lossy().into_owned();
    let _ = std::process::Command::new("launchctl")
        .args(["unload", &p])
        .output();
    if path.exists() {
        std::fs::remove_file(&path).with_context(|| format!("remove {p}"))?;
    }
    println!("✓ localmem service removed (launchd: {LABEL}).");
    Ok(())
}

#[cfg(target_os = "macos")]
fn status() -> Result<()> {
    let installed = plist_path().map(|p| p.exists()).unwrap_or(false);
    let out = std::process::Command::new("launchctl")
        .args(["list", LABEL])
        .output();
    let running = matches!(out, Ok(o) if o.status.success());
    print_status(installed, running);
    Ok(())
}

// ---------------------------------------------------------------------------
// Linux (systemd --user)
// ---------------------------------------------------------------------------

#[cfg(target_os = "linux")]
fn unit_path() -> Result<PathBuf> {
    let base = std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            PathBuf::from(std::env::var("HOME").unwrap_or_default()).join(".config")
        });
    Ok(base.join("systemd/user").join(format!("{LABEL}.service")))
}

#[cfg(target_os = "linux")]
fn install(_home: Option<&str>) -> Result<()> {
    let exe = exe_path()?;
    let path = unit_path()?;
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).context("create systemd user dir")?;
    }
    std::fs::write(&path, systemd_unit(&exe))
        .with_context(|| format!("write {}", path.display()))?;
    let unit = format!("{LABEL}.service");
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .output();
    let out = std::process::Command::new("systemctl")
        .args(["--user", "enable", "--now", &unit])
        .output()
        .context("run systemctl --user enable --now")?;
    if !out.status.success() {
        bail!(
            "systemctl enable failed: {}",
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    println!("✓ localmem service installed (systemd --user: {unit}).");
    println!("  It now starts at login and restarts on failure.");
    println!("  unit: {}", path.display());
    Ok(())
}

#[cfg(target_os = "linux")]
fn uninstall() -> Result<()> {
    let unit = format!("{LABEL}.service");
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "disable", "--now", &unit])
        .output();
    if let Ok(path) = unit_path() {
        if path.exists() {
            std::fs::remove_file(&path).ok();
        }
    }
    let _ = std::process::Command::new("systemctl")
        .args(["--user", "daemon-reload"])
        .output();
    println!("✓ localmem service removed (systemd --user: {unit}).");
    Ok(())
}

#[cfg(target_os = "linux")]
fn status() -> Result<()> {
    let installed = unit_path().map(|p| p.exists()).unwrap_or(false);
    let out = std::process::Command::new("systemctl")
        .args(["--user", "is-active", &format!("{LABEL}.service")])
        .output();
    let running = matches!(out, Ok(o) if String::from_utf8_lossy(&o.stdout).trim() == "active");
    print_status(installed, running);
    Ok(())
}

// ---------------------------------------------------------------------------
// Unsupported platforms
// ---------------------------------------------------------------------------

#[cfg(not(any(target_os = "macos", target_os = "linux")))]
fn install(_home: Option<&str>) -> Result<()> {
    bail!("auto-launch service is supported on macOS (launchd) and Linux (systemd) only; run `localmem serve` manually")
}
#[cfg(not(any(target_os = "macos", target_os = "linux")))]
fn uninstall() -> Result<()> {
    bail!("auto-launch service is not supported on this platform")
}
#[cfg(not(any(target_os = "macos", target_os = "linux")))]
fn status() -> Result<()> {
    println!("auto-launch service: unsupported on this platform (run `localmem serve` manually)");
    Ok(())
}

#[cfg(any(target_os = "macos", target_os = "linux"))]
fn print_status(installed: bool, running: bool) {
    println!(
        "localmem service: {} · {}",
        if installed {
            "installed"
        } else {
            "not installed"
        },
        if running { "running" } else { "not running" }
    );
    if !installed {
        println!("  install with: localmem service install");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn launchd_plist_has_label_exe_and_keepalive() {
        let p = launchd_plist("/usr/local/bin/localmem", "/home/.localmem/serve.log");
        assert!(p.contains("<string>dev.localmem.core</string>"));
        assert!(p.contains("<string>/usr/local/bin/localmem</string>"));
        assert!(p.contains("<string>serve</string>"));
        assert!(p.contains("<key>RunAtLoad</key>"));
        assert!(p.contains("<key>KeepAlive</key>"));
        assert!(p.contains("/home/.localmem/serve.log"));
    }

    #[test]
    fn systemd_unit_has_execstart_and_wantedby() {
        let u = systemd_unit("/usr/local/bin/localmem");
        assert!(u.contains("ExecStart=/usr/local/bin/localmem serve --dashboard"));
        assert!(u.contains("Restart=always"));
        assert!(u.contains("WantedBy=default.target"));
    }

    #[test]
    fn unknown_action_errors() {
        assert!(run("frobnicate", None).is_err());
    }
}
